// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKhP1euN0gUowmUgSW_uypZxfAOCz8H70',
    appId: '1:137390061382:web:bf20837622afd6e16b1747',
    messagingSenderId: '137390061382',
    projectId: 'projectapp-6c852',
    authDomain: 'projectapp-6c852.firebaseapp.com',
    databaseURL: 'https://projectapp-6c852-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projectapp-6c852.firebasestorage.app',
    measurementId: 'G-M5DG0D6FP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXLEnLgA--mThFD04qwRjxdqxN9D33R5E',
    appId: '1:137390061382:android:fd44d9dc7db807dc6b1747',
    messagingSenderId: '137390061382',
    projectId: 'projectapp-6c852',
    databaseURL: 'https://projectapp-6c852-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projectapp-6c852.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBccsOTJp6YjBaEm1Q1wFlbi2oCPdmhH38',
    appId: '1:137390061382:ios:5d5597762a52af546b1747',
    messagingSenderId: '137390061382',
    projectId: 'projectapp-6c852',
    databaseURL: 'https://projectapp-6c852-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projectapp-6c852.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBccsOTJp6YjBaEm1Q1wFlbi2oCPdmhH38',
    appId: '1:137390061382:ios:5d5597762a52af546b1747',
    messagingSenderId: '137390061382',
    projectId: 'projectapp-6c852',
    databaseURL: 'https://projectapp-6c852-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projectapp-6c852.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKhP1euN0gUowmUgSW_uypZxfAOCz8H70',
    appId: '1:137390061382:web:94887f68fe93511b6b1747',
    messagingSenderId: '137390061382',
    projectId: 'projectapp-6c852',
    authDomain: 'projectapp-6c852.firebaseapp.com',
    databaseURL: 'https://projectapp-6c852-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projectapp-6c852.firebasestorage.app',
    measurementId: 'G-L5HZ4ZLEPD',
  );
}
